#pragma once


enum class MessageID 
{ 
	MSG_UNKNOWN,
	MSG_DESTROY_ENTITY,
	MSG_HEARSHRINK_WALK,
	MSG_HEARGROW_RUN,
	MSG_SET_TARGET_PLAYER,
	MSG_HEARSHRINK_STAND,
	MSG_PASSANT_TURN,
	MSG_ADD_DIALOG,
	MSG_ADD_TO_CREATURE_LOG,
	MSG_PAUSE_GAME,
};